language: python
python:
- 3.6
- 3.5
- 2.7
os:
- linux
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: howlanderson
  password:
    secure: X2k80vMF/lbxcC+EFnyWJIDnTvS72toA4kVqpc6AP/5wmen+vSDmfG1HYfb99EyCS63rzGIFwhSmiUb84jCcW39kqWk+27jKogNgZffvThxsZZdwiDd+xhzSqaNcvrVwmYl6Luuu7EdBnrDJMb7TisSRm8q/ZMMFsG5eJytorOAOxB01zqwPAD61eY1Nict0eoTdt/5rS2GX5LGhnV5z5M/DI1W+XX/IE+cnbmSFegTg5BzQJ1uOxjl6vBtYx9LISS4xPi6hp1oTVSm54L851LRwjazLpkS+ZDfz7GBDbXXtSlzgprPJfzSSuRmxwNPrTDL0690+LBCX7EyaLgh96O/HrCtRwrjATMCrz3faaf1c3FOJXuTe1gZ3j2/dAhfp5gsoEjZmX3ZLTO57XaX56AUWWzuJG84FVjkWb7bCHy36O+pdoa12euyvKAfKtRaapXx7NNh3Tph1VihrqCgTIP8c883URDys49CuQu4oLX+Se0B8jYtHbOTX/YftT622xhnd/SQIYbwNug3vQYp53evH7RQB9EaSFv6DOoUiZhHeqAdyF47kNYrs2lLjwIwOZAiotaFaxQVTzF9TJ/8xvAX1e7hKTjGQyJuJdG/7AeYGLTeVQ5SPvz4vpIR5X99mDxsCmmYd3dj+RBSW/BjVSVSFzLlqnJ+lrhul3D0Yo3o=
  on:
    tags: true
    branch: master
    repo: howl-anderson/MicroTokenizer
    python: 3.6
